/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labpro1;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import static java.lang.Math.random;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

//tarea agregar 2 personajes mas, 2 personajes por equipo, que tengan ataques diferentes




/**
 *
 * @author Basico
 */
public class frame1 extends javax.swing.JFrame {
 

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selec = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Personajes = new javax.swing.ButtonGroup();
        Ata1 = new javax.swing.ButtonGroup();
        Ata2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Atacar1 = new javax.swing.JButton();
        vida1 = new javax.swing.JProgressBar();
        vida2 = new javax.swing.JProgressBar();
        game = new javax.swing.JLabel();
        Curarse1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Atacar2 = new javax.swing.JButton();
        vida3 = new javax.swing.JProgressBar();
        vida4 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        R2freddy = new javax.swing.JRadioButton();
        R2raiden = new javax.swing.JRadioButton();
        Combo2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        Rfreddy = new javax.swing.JRadioButton();
        Rraiden = new javax.swing.JRadioButton();
        Combo1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basico\\Desktop\\subzero.jpg")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basico\\Desktop\\Fredypequeño.png")); // NOI18N

        Atacar1.setText("Atacar");
        Atacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Atacar1MousePressed(evt);
            }
        });
        Atacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atacar1ActionPerformed(evt);
            }
        });

        vida1.setBackground(new java.awt.Color(255, 0, 0));
        vida1.setMaximum(1000);
        vida1.setValue(1000);

        vida2.setBackground(new java.awt.Color(255, 0, 0));
        vida2.setForeground(new java.awt.Color(255, 51, 51));
        vida2.setMaximum(1000);
        vida2.setValue(800);

        game.setText("Curso del juego");

        Curarse1.setBackground(new java.awt.Color(51, 51, 255));
        Curarse1.setText("Curar a los 2");
        Curarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Curarse1MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basico\\Desktop\\raidenpequeño.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Basico\\Desktop\\motaropequeño.png")); // NOI18N

        jLabel5.setText("Equipo Li");

        jLabel6.setText("Equipo Nux");

        Atacar2.setText("Atacar");
        Atacar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Atacar2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Atacar2MousePressed(evt);
            }
        });
        Atacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atacar2ActionPerformed(evt);
            }
        });

        vida3.setBackground(new java.awt.Color(255, 0, 0));
        vida3.setForeground(new java.awt.Color(255, 51, 51));
        vida3.setMaximum(1000);
        vida3.setValue(850);

        vida4.setBackground(new java.awt.Color(255, 0, 0));
        vida4.setMaximum(1000);
        vida4.setValue(1000);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personaje a atacar"));

        Ata2.add(R2freddy);
        R2freddy.setText("Freddy");

        Ata2.add(R2raiden);
        R2raiden.setText("Raiden");

        Combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Rayos UV", "Patada de caballo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2raiden)
                    .addComponent(R2freddy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(R2freddy)
                .addGap(18, 18, 18)
                .addComponent(R2raiden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personaje a atacar"));

        Ata1.add(Rfreddy);
        Rfreddy.setText("Freddy");

        Ata1.add(Rraiden);
        Rraiden.setText("Raiden");

        Combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Lluvia de granizo", "Tornado de hielo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rraiden)
                    .addComponent(Rfreddy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Rfreddy)
                .addGap(18, 18, 18)
                .addComponent(Rraiden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Musica");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vida4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(Atacar2))
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Curarse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Atacar1)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(game))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(173, 173, 173)
                .addComponent(jLabel6)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Atacar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Curarse1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Atacar2)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(game)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Atacar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atacar1MousePressed
        // TODO add your handling code here:
        if(Rfreddy.isSelected()){
        double random= Math.random()*15;
        int nlife= vida2.getValue()-10;
        vida2.setValue(nlife);
        
        

        Timer timer= new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
        
        double random=Math.random()*25;
        int vidao=vida1.getValue()-15;
        vida1.setValue(vidao);
        
            }
        });
        timer.setRepeats(false);
        timer.start();
        } else if(Rraiden.isSelected()){
            double random= Math.random()*15;
              int life= vida3.getValue()-10;
               vida3.setValue(life);
               
               
        
        
        Timer timer= new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
        
        double random=Math.random()*15;
       int vidao=vida1.getValue()-15;
        vida1.setValue(vidao);

            }
        });
        timer.setRepeats(false);
        timer.start();
        }
       
            if(Rfreddy.isSelected()){
                 if(Combo1.getSelectedItem().equals("Lluvia de granizo")){
                 int nlife= vida2.getValue()-60;
                    vida2.setValue(nlife);
                    
                    int vidao=vida1.getValue()-40;
                    vida1.setValue(vidao);
                }else if(Combo1.getSelectedItem().equals("Tornado de hielo")){
                 int nlife= vida2.getValue()-50;
                  vida2.setValue(nlife);
                  
                  int vidao=vida1.getValue()-20;
                  vida1.setValue(vidao);
                }else{
                    int nlife= vida2.getValue()-5;
                    vida2.setValue(nlife);
                    
                    int vidao=vida1.getValue()-5;
                    vida1.setValue(vidao);
                }
            }
            
            if(Rraiden.isSelected()){
                 if(Combo1.getSelectedItem().equals("Lluvia de granizo")){
                 int nlife= vida3.getValue()-60;
                    vida3.setValue(nlife);
                    
                    int vidao=vida1.getValue()-38;
                    vida1.setValue(vidao);
                }else if(Combo1.getSelectedItem().equals("Tornado de hielo")){
                 int nlife= vida3.getValue()-50;
                  vida3.setValue(nlife);
                  int vidao=vida1.getValue()-25;
                   vida1.setValue(vidao);
                }else{
                    int nlife= vida3.getValue()-5;
                    vida3.setValue(nlife);
                    int vidao=vida1.getValue()-5;
                    vida1.setValue(vidao);
                }
            }
            if(vida2.getValue()<=0 && vida3.getValue()<=0){
                
                game.setText("Ha ganado el equipo Li");
                Atacar1.setEnabled(false);
                Atacar2.setEnabled(false);
                Atacar1.setVisible(false);
                Atacar2.setVisible(false);
            }else if(vida1.getValue()<=0 && vida4.getValue()<=0){
                game.setText("Ha ganado el equipo Nux");
                Atacar1.setEnabled(false);
                Atacar2.setEnabled(false);
                Atacar1.setVisible(false);
                Atacar2.setVisible(false);
                
            }
            
             if(vida1.getValue()<=0){
                Atacar1.setEnabled(false);
                Atacar1.setVisible(false);
  }
            
            
    }//GEN-LAST:event_Atacar1MousePressed

   
    private void Curarse1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Curarse1MousePressed
        
        int vida= vida1.getValue()+200;
        vida1.setValue(vida);
        
        int vida1=vida4.getValue()+200;
        vida4.setValue(vida1);
        
        
            Curarse1.setEnabled(false);
            Curarse1.setVisible(false);
        
       
            Atacar1.setEnabled(true);
            Atacar1.setVisible(true);
            Atacar2.setEnabled(true);
            Atacar2.setVisible(true);
        
            
            
        
        
        
    
    }//GEN-LAST:event_Curarse1MousePressed

    private void Atacar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atacar2MousePressed
        if(Rfreddy.isSelected()){
        double random= Math.random()*15;
        
        int nvlife= vida2.getValue()-5;
        vida2.setValue(nvlife);

        Timer timer= new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
        
        double random=Math.random()*15;
         int vidao1=vida4.getValue()-5;
         vida4.setValue(vidao1);
        
            }
        });
        timer.setRepeats(false);
        timer.start();
        } else if(Rraiden.isSelected()){
            double random= Math.random()*15;
              int life= vida3.getValue()-5;
               vida3.setValue(life);
               
        
       
        Timer timer= new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
        
        double random=Math.random()*15;
         int vidao1=vida4.getValue()-5;
         vida4.setValue(vidao1);
        
       
            }
        });
        timer.setRepeats(false);
        timer.start();
        }
       
            if(R2freddy.isSelected()){
                 if(Combo2.getSelectedItem().equals("Rayos UV")){
                 int nlife= vida2.getValue()-60;
                    vida2.setValue(nlife);
                    
                     int vidao1=vida4.getValue()-55;
                    vida4.setValue(vidao1);
                }else if(Combo2.getSelectedItem().equals("Patada de caballo")){
                 int nlife= vida2.getValue()-50;
                  vida2.setValue(nlife);
                  
                   int vidao1=vida4.getValue()-40;
                    vida4.setValue(vidao1);
                }else{
                    int nlife= vida2.getValue()-5;
                    vida2.setValue(nlife);
                    
                     int vidao1=vida4.getValue()-5;
         vida4.setValue(vidao1);
                }
            }
            
            if(R2raiden.isSelected()){
                 if(Combo2.getSelectedItem().equals("Rayos UV")){
                 int nlife= vida3.getValue()-60;
                    vida3.setValue(nlife);
                    
                     int vidao1=vida4.getValue()-50;
         vida4.setValue(vidao1);
                }else if(Combo2.getSelectedItem().equals("Patada de caballo")){
                 int nlife= vida3.getValue()-50;
                  vida3.setValue(nlife);
                  
                   int vidao1=vida4.getValue()-38;
         vida4.setValue(vidao1);
                }else{
                    int nlife= vida3.getValue()-5;
                    vida3.setValue(nlife);
                     int vidao1=vida4.getValue()-5;
         vida4.setValue(vidao1);
                }
            }
            
             if(vida2.getValue()<=0 && vida3.getValue()<=0){
                
                game.setText("Ha ganado el equipo Li");
                Atacar1.setEnabled(false);
                Atacar2.setEnabled(false);
                Atacar1.setVisible(false);
                Atacar2.setVisible(false);
            }else if(vida1.getValue()<=0 && vida4.getValue()<=0){
                game.setText("Ha ganado el equipo Nux");
                Atacar1.setEnabled(false);
                Atacar2.setEnabled(false);
                Atacar1.setVisible(false);
                Atacar2.setVisible(false);
                
            }
              if(vida4.getValue()<=0){
                Atacar2.setEnabled(false);
                Atacar2.setVisible(false);
  }
            
        
    }//GEN-LAST:event_Atacar2MousePressed

    private void Atacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atacar2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Atacar2ActionPerformed

    private void Atacar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atacar2MouseClicked
        // TODO add your handling code here:
        
                           
    }//GEN-LAST:event_Atacar2MouseClicked

    private void Atacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atacar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Atacar1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                InputStream music;
        try{
            music=new FileInputStream(new File("src\\assets\\Street.wav"));
            AudioStream audios=new AudioStream(music);
            AudioPlayer.player.start(audios);
        }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
        } 
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Ata1;
    private javax.swing.ButtonGroup Ata2;
    private javax.swing.JButton Atacar1;
    private javax.swing.JButton Atacar2;
    private javax.swing.JComboBox Combo1;
    private javax.swing.JComboBox Combo2;
    private javax.swing.JButton Curarse1;
    private javax.swing.ButtonGroup Personajes;
    private javax.swing.JRadioButton R2freddy;
    private javax.swing.JRadioButton R2raiden;
    private javax.swing.JRadioButton Rfreddy;
    private javax.swing.JRadioButton Rraiden;
    private javax.swing.ButtonGroup Selec;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel game;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar vida1;
    private javax.swing.JProgressBar vida2;
    private javax.swing.JProgressBar vida3;
    private javax.swing.JProgressBar vida4;
    // End of variables declaration//GEN-END:variables
}
    

