/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigopelea;
import java.io.File;
import java.io.FileInputStream;
import java.util.Random;
import java.lang.*;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author Roberto
 */
public class CodigoPeleaVisual extends javax.swing.JFrame {
Random ran = new Random();
    /**
     * Creates new form CodigoPeleaVisual
     */
    public CodigoPeleaVisual() {
        initComponents();
        lbl_ataque_jugador1.setVisible(false);
        lbl_ataque_jugador2.setVisible(false);
        int turno = ran.nextInt(2)+1;
        if(turno==1){
            lbl_turno.setText("JUGADOR 1");
            btn_vida_jugador1.setEnabled(true);
            btn_vida_jugador3.setEnabled(true);
            btn_vida_jugador5.setEnabled(true);
            btn_vida_jugador2.setEnabled(false);
            btn_vida_jugador4.setEnabled(false);
            btn_vida_jugador6.setEnabled(false);
        }
        if(turno==2){
            lbl_turno.setText("JUGADOR 2");
            btn_vida_jugador1.setEnabled(false);
            btn_vida_jugador3.setEnabled(false);
            btn_vida_jugador5.setEnabled(false);
            btn_vida_jugador2.setEnabled(true);
            btn_vida_jugador4.setEnabled(true);
            btn_vida_jugador6.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_vida_jugador2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_vida_jugador1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_music = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lbl_ataque_jugador2 = new javax.swing.JLabel();
        lbl_ataque_jugador1 = new javax.swing.JLabel();
        lbl_game_over = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_turno = new javax.swing.JLabel();
        bar_jugador1 = new javax.swing.JProgressBar();
        bar_jugador2 = new javax.swing.JProgressBar();
        lbl_character1 = new javax.swing.JLabel();
        lbl_character2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_vida_jugador2 = new javax.swing.JButton();
        btn_vida_jugador1 = new javax.swing.JButton();
        lbl_condicion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_condicion2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_vida_jugador4 = new javax.swing.JButton();
        btn_vida_jugador3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_condicion3 = new javax.swing.JLabel();
        lbl_condicion4 = new javax.swing.JLabel();
        btn_vida_jugador6 = new javax.swing.JButton();
        btn_vida_jugador5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_condicion5 = new javax.swing.JLabel();
        lbl_condicion6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_vida_jugador2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_vida_jugador2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vida_jugador2.setText("100");
        getContentPane().add(lbl_vida_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("HP:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 30, -1));

        lbl_vida_jugador1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_vida_jugador1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vida_jugador1.setText("100");
        getContentPane().add(lbl_vida_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 30, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HP:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 30, -1));

        btn_music.setText("Music");
        btn_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_music, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 79, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        lbl_ataque_jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PieceKnightAtkg.png"))); // NOI18N
        lbl_ataque_jugador2.setText("jLabel7");
        getContentPane().add(lbl_ataque_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 370, 200));

        lbl_ataque_jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PieceUnicornAtkG.png"))); // NOI18N
        lbl_ataque_jugador1.setText("jLabel7");
        getContentPane().add(lbl_ataque_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 380, 160));

        lbl_game_over.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        getContentPane().add(lbl_game_over, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 270, 40));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 79, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TURNO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 60, -1));

        lbl_turno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_turno.setText("JUGADOR 1");
        getContentPane().add(lbl_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 90, -1));

        bar_jugador1.setValue(100);
        getContentPane().add(bar_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 20));

        bar_jugador2.setToolTipText("");
        bar_jugador2.setValue(100);
        getContentPane().add(bar_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, 20));

        lbl_character1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PieceUnicornbltG.png"))); // NOI18N
        getContentPane().add(lbl_character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 170, 350, 370));

        lbl_character2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PieceKnightbltG.png"))); // NOI18N
        lbl_character2.setText("jLabel3");
        getContentPane().add(lbl_character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 360, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PopUp Battle Background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        btn_vida_jugador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador2.setText("Sword Slash");
        btn_vida_jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 140, 50));

        btn_vida_jugador1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador1.setText("Rainbow Poop");
        btn_vida_jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 140, 50));

        lbl_condicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion.setText("10");
        getContentPane().add(lbl_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 30, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("/2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 30, -1));

        lbl_condicion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion2.setText("10");
        getContentPane().add(lbl_condicion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, 30, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("/10");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 30, -1));

        btn_vida_jugador4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador4.setText("Tackle");
        btn_vida_jugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, 140, 50));

        btn_vida_jugador3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador3.setText("Slash");
        btn_vida_jugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 140, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("/10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 650, 30, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("/3");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 30, -1));

        lbl_condicion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion3.setText("3");
        getContentPane().add(lbl_condicion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 20, -1));

        lbl_condicion4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion4.setText("3");
        getContentPane().add(lbl_condicion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 710, 20, -1));

        btn_vida_jugador6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador6.setText("Super Attack");
        btn_vida_jugador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 140, 50));

        btn_vida_jugador5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_vida_jugador5.setText("Super Attack");
        btn_vida_jugador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vida_jugador5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vida_jugador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 140, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("/3");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 710, 30, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("/2");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 30, -1));

        lbl_condicion5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion5.setText("2");
        getContentPane().add(lbl_condicion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 20, -1));

        lbl_condicion6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_condicion6.setText("2");
        getContentPane().add(lbl_condicion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vida_jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador1ActionPerformed
        lbl_ataque_jugador2.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 1")){
            InputStream music;
            int condicion = Integer.parseInt(lbl_condicion.getText());
            if (condicion>=1){
                condicion--;
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                int x = ran.nextInt(15)+1;
                int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
                lbl_ataque_jugador1.setVisible(true);
                vida_jugador2-=x;
            if(vida_jugador2<=0){
                vida_jugador2=0;
                lbl_game_over.setText("El jugador 1 ha ganado!");  
                lbl_character2.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            }
        }
        else{
            lbl_turno.setText("JUGADOR 2");
        }
        bar_jugador2.setValue(vida_jugador2-x);
        lbl_vida_jugador2.setText(""+vida_jugador2);
        lbl_condicion.setText(""+condicion);
            }
            if(lbl_turno.getText().equals("JUGADOR 2")){
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(true);
                btn_vida_jugador4.setEnabled(true);
                btn_vida_jugador6.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_btn_vida_jugador1ActionPerformed

    private void btn_vida_jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador2ActionPerformed
        lbl_ataque_jugador1.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 2")){
            InputStream music, music2;
            int condicion = Integer.parseInt(lbl_condicion2.getText());
            if (condicion>=1){
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                condicion--;
                int x = ran.nextInt(15)+1;    
                int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
                lbl_ataque_jugador2.setVisible(true);
                vida_jugador1-=x;
            if(vida_jugador1<=0){
                vida_jugador1=0;
                lbl_game_over.setText("El jugador 2 ha ganado!");
                lbl_character1.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
                }
            }
        else{
            lbl_turno.setText("JUGADOR 1");
        }
        bar_jugador1.setValue(vida_jugador1-x);
        lbl_vida_jugador1.setText(""+vida_jugador1);
        lbl_condicion2.setText(""+condicion);
            }
       }
        if(lbl_turno.getText().equals("JUGADOR 1")){
                btn_vida_jugador1.setEnabled(true);
                btn_vida_jugador3.setEnabled(true);
                btn_vida_jugador5.setEnabled(true);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
            }
        
    }//GEN-LAST:event_btn_vida_jugador2ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        if(lbl_game_over.getText().equals("El jugador 1 ha ganado!") || lbl_game_over.getText().equals("El jugador 2 ha ganado!")){
           lbl_ataque_jugador1.setVisible(false);
           lbl_ataque_jugador2.setVisible(false);
           bar_jugador1.setValue(100);
           bar_jugador2.setValue(100);
           int vida_jugador1 = 100;
           lbl_vida_jugador1.setText(""+vida_jugador1);
           int vida_jugador2 = 100;
           lbl_vida_jugador2.setText(""+vida_jugador2);
           int turno = ran.nextInt(2)+1;
            if(turno==1){
                lbl_turno.setText("JUGADOR 1");
                btn_vida_jugador1.setEnabled(true);
                btn_vida_jugador3.setEnabled(true);
                btn_vida_jugador5.setEnabled(true);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
            }
            if(turno==2){
                lbl_turno.setText("JUGADOR 2");
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(true);
                btn_vida_jugador4.setEnabled(true);
                btn_vida_jugador6.setEnabled(true);
            }
            lbl_character1.setEnabled(true);
            lbl_character2.setEnabled(true);
            
                    
           int condicion1 = 10;
           lbl_condicion.setText(""+condicion1);
           int condicion2 = 10;
           lbl_condicion2.setText(""+condicion2);
           int condicion3 = 3;
           lbl_condicion3.setText(""+condicion3);
           int condicion4 = 3;
           lbl_condicion4.setText(""+condicion4);
           int condicion5 = 2;
           lbl_condicion5.setText(""+condicion5);
           int condicion6 = 2;
           lbl_condicion6.setText(""+condicion6);
           
           
           lbl_game_over.setText("");   
        }
       
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musicActionPerformed
        InputStream music;
try{
music=new FileInputStream(new File("src\\assets\\Street.wav"));
AudioStream audios=new AudioStream(music);
AudioPlayer.player.start(audios);
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
} 
    }//GEN-LAST:event_btn_musicActionPerformed

    private void btn_vida_jugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador3ActionPerformed
        lbl_ataque_jugador2.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 1")){
            InputStream music;
            int condicion = Integer.parseInt(lbl_condicion3.getText());
            if (condicion>=1){
                condicion--;
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                int x = ran.nextInt(18)+2;
                int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
                lbl_ataque_jugador1.setVisible(true);
                vida_jugador2-=x;
            if(vida_jugador2<=0){
                vida_jugador2=0;
                lbl_game_over.setText("El jugador 1 ha ganado!");  
                lbl_character2.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            }
        }
        else{
            lbl_turno.setText("JUGADOR 2");
        }
        bar_jugador2.setValue(vida_jugador2-x);
        lbl_vida_jugador2.setText(""+vida_jugador2);
        lbl_condicion3.setText(""+condicion);
            }
            if(lbl_turno.getText().equals("JUGADOR 2")){
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador6.setEnabled(true);
                btn_vida_jugador2.setEnabled(true);
                btn_vida_jugador4.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_btn_vida_jugador3ActionPerformed

    private void btn_vida_jugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador4ActionPerformed
        lbl_ataque_jugador1.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 2")){
            InputStream music;
            int condicion = Integer.parseInt(lbl_condicion4.getText());
            if (condicion>=1){
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                condicion--;
                int x = ran.nextInt(18)+2;    
                int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
                lbl_ataque_jugador2.setVisible(true);
                vida_jugador1-=x;
            if(vida_jugador1<=0){
                vida_jugador1=0;
                lbl_game_over.setText("El jugador 2 ha ganado!");  
                lbl_character1.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            }
            }
        else{
            lbl_turno.setText("JUGADOR 1");
        }
        bar_jugador1.setValue(vida_jugador1-x);
        lbl_vida_jugador1.setText(""+vida_jugador1);
        lbl_condicion4.setText(""+condicion);
            }
       }
        if(lbl_turno.getText().equals("JUGADOR 1")){
                btn_vida_jugador1.setEnabled(true);
                btn_vida_jugador3.setEnabled(true);
                btn_vida_jugador5.setEnabled(true);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
            }
        
    }//GEN-LAST:event_btn_vida_jugador4ActionPerformed

    private void btn_vida_jugador5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador5ActionPerformed
        lbl_ataque_jugador2.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 1")){
            InputStream music;
            int condicion = Integer.parseInt(lbl_condicion5.getText());
            if (condicion>=1){
                condicion--;
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                int x = ran.nextInt(25)+2;
                int vida_jugador2 = Integer.parseInt(lbl_vida_jugador2.getText());
                lbl_ataque_jugador1.setVisible(true);
                vida_jugador2-=x;
            if(vida_jugador2<=0){
                vida_jugador2=0;
                lbl_game_over.setText("El jugador 1 ha ganado!"); 
                lbl_character2.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            }
        }
        else{
            lbl_turno.setText("JUGADOR 2");
        }
        bar_jugador2.setValue(vida_jugador2-x);
        lbl_vida_jugador2.setText(""+vida_jugador2);
        lbl_condicion5.setText(""+condicion);
            }
            if(lbl_turno.getText().equals("JUGADOR 2")){
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(true);
                btn_vida_jugador4.setEnabled(true);
                btn_vida_jugador6.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_btn_vida_jugador5ActionPerformed

    private void btn_vida_jugador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vida_jugador6ActionPerformed
       lbl_ataque_jugador1.setVisible(false);
        if(lbl_turno.getText().equals("JUGADOR 2")){
            InputStream music;
            int condicion = Integer.parseInt(lbl_condicion6.getText());
            if (condicion>=1){
                try {
                    music = new FileInputStream(new File("src\\assets\\PUNCH.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            } 
                condicion--;
                int x = ran.nextInt(25)+2;    
                int vida_jugador1 = Integer.parseInt(lbl_vida_jugador1.getText());
                lbl_ataque_jugador2.setVisible(true);
                vida_jugador1-=x;
            if(vida_jugador1<=0){
                vida_jugador1=0;
                lbl_game_over.setText("El jugador 2 ha ganado!");
                lbl_character1.setEnabled(false);
                lbl_ataque_jugador1.setVisible(false);
                lbl_ataque_jugador2.setVisible(false);
                btn_vida_jugador1.setEnabled(false);
                btn_vida_jugador3.setEnabled(false);
                btn_vida_jugador5.setEnabled(false);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
                try {
                    music = new FileInputStream(new File("src\\assets\\Yay.wav"));
                    AudioStream audios=new AudioStream(music);
                    AudioPlayer.player.start(audios);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
            }
            }
        else{
            lbl_turno.setText("JUGADOR 1");
        }
        bar_jugador1.setValue(vida_jugador1-x);
        lbl_vida_jugador1.setText(""+vida_jugador1);
        lbl_condicion6.setText(""+condicion);
            }
       }
        if(lbl_turno.getText().equals("JUGADOR 1")){
                btn_vida_jugador1.setEnabled(true);
                btn_vida_jugador3.setEnabled(true);
                btn_vida_jugador5.setEnabled(true);
                btn_vida_jugador2.setEnabled(false);
                btn_vida_jugador4.setEnabled(false);
                btn_vida_jugador6.setEnabled(false);
            }
    }//GEN-LAST:event_btn_vida_jugador6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodigoPeleaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodigoPeleaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodigoPeleaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodigoPeleaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodigoPeleaVisual().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar_jugador1;
    private javax.swing.JProgressBar bar_jugador2;
    private javax.swing.JButton btn_music;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_vida_jugador1;
    private javax.swing.JButton btn_vida_jugador2;
    private javax.swing.JButton btn_vida_jugador3;
    private javax.swing.JButton btn_vida_jugador4;
    private javax.swing.JButton btn_vida_jugador5;
    private javax.swing.JButton btn_vida_jugador6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_ataque_jugador1;
    private javax.swing.JLabel lbl_ataque_jugador2;
    private javax.swing.JLabel lbl_character1;
    private javax.swing.JLabel lbl_character2;
    private javax.swing.JLabel lbl_condicion;
    private javax.swing.JLabel lbl_condicion2;
    private javax.swing.JLabel lbl_condicion3;
    private javax.swing.JLabel lbl_condicion4;
    private javax.swing.JLabel lbl_condicion5;
    private javax.swing.JLabel lbl_condicion6;
    private javax.swing.JLabel lbl_game_over;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JLabel lbl_vida_jugador1;
    private javax.swing.JLabel lbl_vida_jugador2;
    // End of variables declaration//GEN-END:variables
}
